[Defines]
    workdir = "Z:\\src\\basetools"
    projectname = "Ovmf"
    workspace = "Z:\\src\\basetools"
    cache_dir = ""

[[Repo]]
    name = 'edk2'
    git = 'https://github.com/tianocore/edk2.git'
    branch = 'master'
    version = 'head'

[Basic]
    [[Basic.step]]
        name = "SetupEnv"
        depends = []
        [Basic.step.command]
            cmd = "EdkSetup.bat"
            parameters = ["Rebuild"]
        output_type = ['EnvVar','File']
    [[Basic.step]]
        name = "BuildClean"
        depends = []
        [Basic.step.command]
            cmd = 'build'
            parameters = ['cleanall','-p','OvmfPkg\OvmfPkgX64.dsc', '-a', 'X64', '-t', 'VS2015x86', '-b', 'RELEASE']
        output_type = ['File']
    [[Basic.step]]
        name = "BuildPlatform"
        depends = []
        [Basic.step.command]
            cmd = 'build'
            parameters = ['-p','OvmfPkg\OvmfPkgX64.dsc', '-a', 'X64', '-t', 'VS2015x86', '-b', 'RELEASE','-y','report.txt']
        output_type = ['File']
    
[BuildCache]
    [[BuildCache.step]]
        name = "SetupEnv"
        depends = []
        [BuildCache.step.command]
            cmd = "EdkSetup.bat"
            parameters = ["Rebuild"]
        output_type = ['EnvVar','File']
    [[BuildCache.step]]
        name = "BuildClean"
        depends = []
        [BuildCache.step.command]
            cmd = 'build'
            parameters = ['cleanall','-p','OvmfPkg\OvmfPkgX64.dsc', '-a', 'X64', '-t', 'VS2015x86', '-b', 'RELEASE']
        output_type = ['File']
    [[BuildCache.step]]
        name = "BuildPlatform"
        depends = []
        [BuildCache.step.command]
            cmd = 'build'
            parameters = ['--hash', '--binary-destination=BINCACHEDEST', '-p','OvmfPkg\OvmfPkgX64.dsc', '-a', 'X64', '-t', 'VS2015x86', '-b', 'RELEASE','-y','report.txt']
        output_type = ['File']
